# Generated by Django 3.2.15 on 2022-08-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_followerscount_likepost_post_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
